#Enable or disable debug information
debug: false
#Enable or disable metrics
metrics: true
#Auto add players to a lottery
lotteryAutoJoin:
  use: false
  lottery: THE_LOTTERY_YOU_WANT_TO_ADD_PLAYERS_TO
#DO NOT TOUCH THIS IT WILL ERASE YOUR CONFIG
configVersion: 0