#Enable or disable debug information
debug: false
#Enable or disable metrics
metrics: true
#Announce different plugin events
announce:
  createLottery: true
  closeLottery: true
#DO NOT TOUCH THIS IT WILL ERASE YOUR CONFIG
configVersion: 0