name: LotteryPlus
version: 1.0.2-B34
description: Create multiple lotteries and pick one or multiple winners.
author: Chaka
main: com.chaka15205.lotteryplus.LotteryPlus
commands:
  lottery:
    description: The Main Command
    usage: /<command>
  ladmin:
    description: The LotteryAdmin Command
    usage: /<command>
permissions:
  lotteryplus.*:
    descripdion: Full access to the plugin.
    default: op
    children:
      lotteryplus.admin: true
      lotteryplus.player: true
  lotteryplus.admin:
    description: Access to admin commands.
    default: false
    children:
      lotteryplus.cmd.lotteryadmin.create: true
      lotteryplus.cmd.lotteryadmin.delete: true
      lotteryplus.cmd.lotteryadmin.add: true
      lotteryplus.cmd.lotteryadmin.remove: true
      lotteryplus.cmd.lotteryadmin.close: true
  lotteryplus.player:
    description: The basic player commands.
    default: false
    children:
      lotteryplus.cmd.lottery.enter: true
      lotteryplus.cmd.lottery.leave: true
      lotteryplus.cmd.lottery.list: true
