name: LotteryPlus
version: 1.0.0-B25
description: Create multiple lotteries and pick one or multiple winners.
author: Chaka
main: com.chaka15205.lotteryplus.LotteryPlus
commands:
  lottery:
    description: The Main Command
    usage: /<command>
  lotteryadmin:
    description: The LotteryAdmin Command
    ailases: [ladmin]
    usage: /<command>
permissions:
  lotteryplus.*:
    descripdion: Full access to the plugin.
    children:
      lotteryplus.admin: true
      lotteryplus.player: true
  lotteryplus.admin:
    description: Access to admin commands.
    children:
      lotteryplus.cmd.lotteryadmin.create: true
      lotteryplus.cmd.lotteryadmin.delete: true
      lotteryplus.cmd.lotteryadmin.add: true
      lotteryplus.cmd.lotteryadmin.remove: true
      lotteryplus.cmd.lotteryadmin.close: true
  lotteryplus.player:
    description: The basic player commands.
    children:
      lotteryplus.cmd.lottery.enter: true
      lotteryplus.cmd.lottery.leave: true
      lotteryplus.cmd.lottery.list: true
